### PR TITLE
Fix for deserializing CronExpression using Json Serializer throwing exception on GetNextValidTimeAfter

### LINKED ISSUE #1996: CronExpression.GetNextValidTimeAfter NullReferenceException when JSON Deserialized.
**Describe the bug**

A contract with a CronExpression property serialized to JSON and stored (forexample using Azure storage), then dezerialized, will throw NullReferenceException when GetNextValidTimeAfter is called.

**Version used**

3.6.2

**To Reproduce**

- Create a CronExpression instance with a valid cron string.
- Call GetNextValidTimeAfter on the created.
- Serialize to JSON, deserialize JSON to new CronExpression instance.
- Call GetNextValidTimeAfter on the new instance.

**Expected behavior**

Expectation would be for GetNextValidTimeAfter to not throw exception, instead return proper data.

**Additional context**

### PR DESCRIPTION
**Pull request by jafin**
## Fix

When deserializing a CronExpression outside of builtin Quartz Serializers (for example to store in a custom store). Then calling `GetNextValidTimeAfter` will throw a NullReferenceException

This is due to `BuildExpression` not being called

Resolves #1996

### CODE REVIEW

File: src/Quartz/CronExpression.cs [hunk 1]
```diff
@@ -433,6 +433,7 @@ protected CronExpression(SerializationInfo info, StreamingContext context)
                     ThrowHelper.ThrowNotSupportedException($"Unknown serialization version {version}");
                     break;
             }
+            BuildExpression(CronExpressionString);
```
Comment (lahma) [inline src/Quartz/CronExpression.cs:436]: Because there's already `OnDeserialization` implemented, doesn't it make the logic run twice wasting cycles in non-JSON context?

Comment (jafin) [reply src/Quartz/CronExpression.cs:436]: 1) Yes, I can confirm what you say that the existing serialization/deserilization will trigger OnDeserilization method, so running BuildExpression twice, (bad).

2) From what I read, System.Text.json and it appears newtonsoft default settings, do not trigger OnDeserialization.  Therefore should a person utilise these to serialize/deserialize the OnDeserilization method are not called. (https://stackoverflow.com/questions/67222737/ondeserialized-is-not-called-in-net-core)

3) can I propose two options:

a) Drop `OnDeserializaiton`, given that it only calls `BuildExpression`, and keep the PR'd BuildExpression in `CronExpression(SerializationInfo info, StreamingContext context)`.

b) Keep `OnDeserialization` as is, utilise the existing `bool expressionParsed` property (which appears unused) to flag Build has occured and conditionally skip in `protected CronExpression(SerializationInfo info, StreamingContext context)`

Thoughts?

Comment (lahma) [reply src/Quartz/CronExpression.cs:436]: maybe go with A, removing the callback/interface would be breaking change but as this is gargeting main I guess it's fine

Comment (jafin) [reply src/Quartz/CronExpression.cs:381]: ok done.

**Review by lahma — APPROVED** [review]

**Comment by lahma** [comment]
Thank you!
